### ISSUE TITLE
Create format for bucket names

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/Data-Delivery-System#279]
- [x] Decide on format
- [x] Add bucket column to DB
- [x] Insert bucket name into project entries

```
import datetime
now = datetime.datetime.now()
timestamp = f"{now.year}{now.month}{now.day}{now.hour}{now.minute}{now.second}{now.microsecond}"
bucket_name = f"<projectID>_{timestamp}_{os.urandom(4).hex()}" 
```
